spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vocabulary-notebook
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  flyway:
    enabled: false
server:
  port: 8080
openai:
  api:
    key:
    endpoint: https://api.openai.com/v1/chat/completions
    deployment-model-id: gpt-3.5-turbo